defaults:
  - dset: qm9
  - encoder: cnn
  - decoder: decoder_global
  - override hydra/job_logging: custom
  - _self_

debug: False
wandb: False
seed: 1234
nf_pretrained_path: "/net/dali/home/mscbio/emg386/weights/nf_qm9_20260330_frozen"
nffm_pretrained_path: "/net/dali/home/mscbio/emg386/weights/nffm_qm9_20260504_145714_635534"
exp_dir: "/net/dali/home/mscbio/emg386/nffm/exp"
exp_name: "t_data_${dset.dset_name}_${now:%Y%m%d}_${now:%H%M%S}_${now:%f}"
dirname: "${exp_dir}/${exp_name}"
codes_dir: "/net/dali/home/mscbio/emg386/weights/nf_qm9_rotation_1_frozen"
plots_path: "/net/dali/home/mscbio/emg386/rfmt"

# data params
normalize_codes: 1
on_the_fly: False
num_augmentations: null

# training params
n_epochs: 100 # for both interpolation and sampled based training
dset:
  batch_size: 128
decoder:
  code_dim: 1024

# for nffm sampling-based training
num_samples: 64
num_steps: 100
n_epochs_train: 20
n_epochs_val: 5
# wandb: True

# output directory for collecting data
out_dir: "${dirname}/t_data"

# output for mlp info
mlp_out_dir: "${dirname}/mlp"

# set the running dir
hydra:
  run:
    dir: ./${dirname}
  job:
    config:
      override_dirname:
        kv_sep: ""
        item_sep: "_"
        exclude_keys: ["exp_dir"]